mysql:
  host: 10.0.50.15
  port: 3306
  username: duanju
  password: netjoy@duanju
  database: duanju
  charset: utf8mb4
  timeout: 60s

redis:
  address: 127.0.0.1:6379
  password:
  database: 0


wx:
  appid: wxe814fe9772dcc6df
  mchid: 1616436352
  key: 636x44f9y3OqN65DRbrh4Zqydobt6MBW


server:
  host: 0.0.0.0
  port: 3333